version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: face_rec
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
